### ISSUE TITLE
Batch LK does not handle batch?

### ISSUE THREAD

**Issue by tobyclh** [facebookresearch/supervision-by-registration#17]
Hello,
Thank you for the code, its great to see LK operation in PyTorch.
I notice the batch LK operation currently only support batch size equals to 1,
is it intentional? and is there any way to make the batch dimension >1?

**Comment by D-X-Y** [comment]
Hi, it is intentional to assume the first dimension of the feature being 1, instead, I perform batch operation on the number-of-points dimension. I did not find a very efficient way to perform the batch operation for different images with multiple different points. If you have any idea, please let me know.
