### ISSUE TITLE
Some questions about the different configs in the "specify_parameter" function in the cpm_vgg16.py

### ISSUE THREAD

**Issue by SunnyDp** [facebookresearch/supervision-by-registration#35]
Thanks to your great job! I have some problems about the the “param_dict” variable in the "specify_parameter" function. The function aims to get the parameters from the model, right? But it has some different parameter settings, such as different lr and bias=false/true...Why one model has many different param settings?

**Comment by D-X-Y** [comment]
`specify_parameter` aims to make different layers to have different learning rates. Since our base detector is convolutional pose machine (CPM), we follow their training setup (https://github.com/shihenw/convolutional-pose-machines-release/blob/master/training/genProto.py#L62), which uses different LR for different layers.
