### ISSUE TITLE
How to make the model smaller?

### ISSUE THREAD

**Issue by zhang-zx** [facebookresearch/supervision-by-registration#43]
Hi, thanks for your great work. Well, I want to make the model small enough to run on a phone. Is is possible to make the model's flops less than 1G? If it is possible, which part should I change in your code? Thanks very much!

**Comment by D-X-Y** [comment]
It is simple. You can change the number of channel in https://github.com/facebookresearch/supervision-by-registration/blob/master/lib/models/cpm_vgg16.py#L19 , a smaller channel will result in smaller FLOPs. Since we use the VGG-16 backbone, you can also use other smaller backbone, such as MobileNet. You need to create a model file and correspondingly modify https://github.com/facebookresearch/supervision-by-registration/blob/master/lib/models/basic.py#L10 . Lastly, replace the arch arg in config files, such as https://github.com/facebookresearch/supervision-by-registration/blob/master/configs/Detector.config#L2

**Comment by zhang-zx** [comment]
Am I right that the lk procedure use rgb images as input? So there's nothing I need to change in that part? And is it ok that I use stages=1 in Detector.config?

**Comment by D-X-Y** [comment]
Yes, you are correct, but stage=1 may obtain a worse NME result.

**Comment by zhang-zx** [comment]
I find it really slow when training with 300VW, is there any way I can accelerate the procedure?

**Comment by D-X-Y** [comment]
Yes, I also suffer from the slow LK operation. We are working on extension work, which can significantly improve the training speed and should be publicly available soon. Please wait maybe about one month~
