### ISSUE TITLE
Could you explain the algorithm in find_tensor_peak_batch?

### ISSUE THREAD

**Issue by KeyKy** [facebookresearch/supervision-by-registration#5]
Why do you use affine_grid and grid_sample？
```
  affine_parameter = torch.zeros((num_pts, 2, 3))
  affine_parameter[:,0,0] = (boxes[2]-boxes[0])/2
  affine_parameter[:,0,2] = (boxes[2]+boxes[0])/2
  affine_parameter[:,1,1] = (boxes[3]-boxes[1])/2
  affine_parameter[:,1,2] = (boxes[3]+boxes[1])/2
  # extract the sub-region heatmap
  theta = affine_parameter.to(heatmap.device)
  grid_size = torch.Size([num_pts, 1, radius*2+1, radius*2+1]) # 69 x 1 x 9 x 9
  grid = F.affine_grid(theta, grid_size) # 69 x 9 x 9 x 2
  sub_feature = F.grid_sample(heatmap.unsqueeze(1), grid).squeeze(1)
  sub_feature = F.threshold(sub_feature, threshold, np.finfo(float).eps)
```
----

What's the algorithm used in base detector?

**Comment by endoplasmic1357** [comment]
This portion is trying to make argmax differentiable. So once the approximate location is found with argmax, a subregion is cropped and a weighted sum between confidence values & (x, y) is computed to find the sub-pixel level (x, y) coordinates. The cropping uses affine_grid and grid_sample so that it is differentiable.

The base detector uses VGG16.
