### ISSUE TITLE
What is the size of the training model?

### ISSUE THREAD

**Issue by hyb1234hi** [facebookresearch/supervision-by-registration#61]
Will the face training model be larger than 10m in size?

In addition, can the algorithm be used commercially?

Can it be used for camera tracking? If so, what's the resolution?

**Comment by xfj81525** [comment]
the project performs not as it described, first original model is very large, approximately 130M, not sutiable for mobile usage,
second， landmark detection effects is very bad for side face ,when the distance is more than 2 meters

**Comment by D-X-Y** [comment]
Thanks for your interest. The training model is based on CPM. Difference configuration could cause the different model size and inference speed. I show the model size of one configuration at here: https://github.com/D-X-Y/landmark-detection/tree/master/TS3#model-configs . 16.70 MB with 1.7 G FLOPs. You can modify configuration or model definition for your target device.

For mobile usage, one could switch the detection model to some light-weight detection model, such as MobileNet-V2 backbone with linear regression. Our SBR is not designed for one specific model but can generalize to different detectors.

The bad performance on side face could be caused by poor base detector, small training data, many failure cases of LK on side faces.

**Comment by xfj81525** [comment]
thanks for your response, by the way , Do you test the side face effect with your internal trained model. for the open demonstration, only front face detection effect is shown and the distance looks like not so far away.

**Comment by D-X-Y** [comment]
We did test our model on internal data one year ago. The internal data has some side faces. Our internal data is high-resolution face image and moreover, the movement of each landmark between two frames is not large. On such data, our performance is fine.

**Comment by hyb1234hi** [comment]
Thank you very much for your reply and look forward to the release of mobile version in the future.

**Comment by D-X-Y** [comment]
No worries. Thanks for the constructive discussion.
