### ISSUE TITLE
About the training time on 300VW

### ISSUE THREAD

**Issue by marvin521** [facebookresearch/supervision-by-registration#7]
Hi thank for the wonderful code.  I have trained the SBR on the demo video (a single video), which takes about 8hours. Thus, I wanna know that how much time it will take to train a model the 300VW dataset?  and what is the value of the epoches?  Thanks in advance.

BTW,  It seems that the evaluation code (which is shown in the following) uses the CPM model. Why don't use the SBR model?

  "python ./exps/eval.py --image ./cache_data/cache/self.jpeg --model ./snapshots/300W-CPM-DET/checkpoint/cpm_vgg16-epoch-049-050.pth --face 250 150 900 1100 --save ./cache_data/cache/test.jpeg"

**Comment by D-X-Y** [comment]
Hi, thanks for the question. In our experiments, we train SBR on multiple Titan V GPUs, and it takes several days to train a model on 300VW. The LK operation costs much time due to the poor implementation, even if it has a very low theoretical computation cost. You can simply replace the CPM model by the SBR model in the script for evaluation. Due to the legal problems, it is inconvenient to provide our trained SBR model, therefore, we use the CPM model for example.

**Comment by marvin521** [comment]
Thanks for quickly response.
