### ISSUE TITLE
The scrips of training sbr model on multiple-videos

### ISSUE THREAD

**Issue by qiexing** [facebookresearch/supervision-by-registration#8]
It's very kind of you to share the code.
I want to training sbr model with multiple videos.
I just use the 300VW as example.
And I change the scrips as this:
![sbr_multiple_video](https://user-images.githubusercontent.com/8178397/42018343-659eeebe-7ae4-11e8-88ea-d3bd98c6d558.png)
Sometimes it will report: no-det loss.
![image](https://user-images.githubusercontent.com/8178397/42018387-8a29a7c4-7ae4-11e8-82c3-33fe4ff5e933.png)
Sometimes it will report: no detection loss and no lk loss.
![image](https://user-images.githubusercontent.com/8178397/42024587-2843b386-7af5-11e8-9c51-c87c2eabcd58.png)
I wonder if this is common ? 
Or can you share an example of training with multiple videos?
Thanks!

**Comment by qiexing** [comment]
This is the example of current video frame list
[300VW.train.lst003.none.refine.txt](https://github.com/facebookresearch/supervision-by-registration/files/2144455/300VW.train.lst003.none.refine.txt)

**Comment by qiexing** [comment]
This is the example of current video frame file.
[300VW.train.lst003.none.refine.txt](https://github.com/facebookresearch/supervision-by-registration/files/2144461/300VW.train.lst003.none.refine.txt)
Is there something wrong?

**Comment by D-X-Y** [comment]
It is fine, each line corresponds to one training batch, as you use too many unlabeled frames, images in one batch data might have no annotation (all of them are from videos). no-lk loss indicates that in that training batch, all lk tracking results are filtered due to the these are unreliable. I suggest that you could increase the proportion of labeled data in the training set.

**Comment by qiexing** [comment]
Thanks for your reply !
